language: generic

dist: trusty
sudo: required

cache:
    apt: true

matrix:
    include:
    - env: CXX=g++-6 CC=gcc-6
      addons:
        apt:
          packages:
            - g++-6
          sources: &sources
            - ubuntu-toolchain-r-test
    - env: CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
          sources: *sources
    - env: CXX=g++-4.9 CC=gcc-4.9
      addons:
        apt:
          packages:
            - g++-4.9
          sources: *sources
    - env: CXX=g++-4.8 CC=gcc-4.8
      addons:
        apt:
          packages:
            - g++-4.8
          sources: *sources

script:
    - ./build_and_test.sh

before_install:
    - ./before_install.sh
