language: generic

cache:
    apt: true

matrix:
    include:
    - env: CXX=g++-6 CC=gcc-6
      addons:
        apt:
          packages:
            - g++-6
            - cmake
          sources: &sources
            - ubuntu-toolchain-r-test
            - kalakris-cmake
    - env: CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
            - cmake
          sources: *sources
    - env: CXX=g++-4.9 CC=gcc-4.9
      addons:
        apt:
          packages:
            - g++-4.9
            - cmake
          sources: *sources
    - env: CXX=g++-4.8 CC=gcc-4.8
      addons:
        apt:
          packages:
            - g++-4.8
            - cmake
          sources: *sources

script:
    - mkdir build && cd build
    - cmake -DUNITTEST=ON ..
    - make
    - make unittest

before_install:
    # Install GTest
    - export GTEST_VERSION=master
    - export GTEST=googletest-${GTEST_VERSION}
    - wget https://github.com/google/googletest/archive/${GTEST_VERSION}.tar.gz
    - tar -xzvf *.tar.gz
    - cd ${GTEST}
    - mkdir build && cd build
    - cmake ..
    - make -j4 && sudo make install && cd ../..


